/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaransks;

import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class editProfile extends javax.swing.JFrame {

    public Connection con;
    public Statement stmt;
    public PreparedStatement prs;
    public isiSKS isiSKS;
    public login login;
    
    private JTextField parameter;
    
    public void koneksian () {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendaftaran","root","");
            stmt = con.createStatement();
            
        } catch (Exception E) {
            JOptionPane.showMessageDialog(null,"Salah Prosedur");
        }
    
    }
    
    public editProfile(){
    initComponents();
    setLocationRelativeTo(null);
    
    }
    
    public editProfile(JLabel parameter) {
        initComponents();
        setLocationRelativeTo(null);
        koneksian();
        
        editNama.setText(parameter.getText());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameBaru = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        editNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("edit profile");

        jLabel3.setText("username baru");

        jLabel4.setText("password baru");

        jLabel5.setText("konfirmasi password");

        jButton1.setText("ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameBaru, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(password1)
                    .addComponent(password2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (String.valueOf(password1.getPassword()).equals("") && String.valueOf(password2.getPassword()).equals("")) {
        int konfirmasi; 
        konfirmasi = JOptionPane.showConfirmDialog(null,"Anda hanya akan mengganti username anda, \napakah anda yakin ??"); 
        if(konfirmasi==JOptionPane.YES_OPTION){ 
            try {
            String sql = "update mahasiswa set username = '"+usernameBaru.getText()+"' where nama_Mahasiswa = '"+editNama.getText()+"'";
            prs = con.prepareStatement(sql);
            prs.execute();
            JOptionPane.showMessageDialog(null, "username anda sudah di update");
            usernameBaru.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "salah prosedur " +e);
            }
        } 
        else{
            //JOptionPane.showMessageDialog(null, "gagal mengupdate data");
        }
        } 
        else if (usernameBaru.getText().equals("")) {
            if (String.valueOf(password1.getPassword()).equals(String.valueOf(password2.getPassword()))) {
        int konfirmasi; 
        konfirmasi = JOptionPane.showConfirmDialog(null,"Anda hanya akan mengganti password anda, \napakah anda yakin ??"); 
        if(konfirmasi==JOptionPane.YES_OPTION){ 
            try {
            String sql = "update mahasiswa set password = '"+String.valueOf(password1.getPassword())+"' where nama_Mahasiswa = '"+editNama.getText()+"'";
            prs = con.prepareStatement(sql);
            prs.execute();
            JOptionPane.showMessageDialog(null, "password anda sudah di update");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "salah prosedur " +e);
            }
        } 
        else{
            //JOptionPane.showMessageDialog(null, "gagal mengupdate data");
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "password belum cocok");
        }
        } else {
            if (String.valueOf(password1.getPassword()).equals(String.valueOf(password2.getPassword()))) {
        int konfirmasi; 
        konfirmasi = JOptionPane.showConfirmDialog(null,"Anda hanya akan mengganti username dan password anda, \napakah anda yakin ??"); 
        if(konfirmasi==JOptionPane.YES_OPTION){ 
            try {
            String sql = "update mahasiswa set username = '"+usernameBaru.getText()+"', password = '"+String.valueOf(password1.getPassword())+"' where nama_Mahasiswa = '"+editNama.getText()+"'";
            prs = con.prepareStatement(sql);
            prs.execute();
            JOptionPane.showMessageDialog(null, "username anda sudah di update");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "salah prosedur " +e);
            }
        } 
        else{
            //JOptionPane.showMessageDialog(null, "gagal mengupdate data");
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Password belum cocok");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int out; 
        out = JOptionPane.showConfirmDialog(null,"akan kembali ke form login, yakin ??"); 
        if(out==JOptionPane.YES_OPTION){ 
            isiSKS = new isiSKS(editNama);
            isiSKS.setVisible(true);
            this.dispose();
        } 
        else{}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField usernameBaru;
    // End of variables declaration//GEN-END:variables
}
