/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaransks;

import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JOptionPane;


public class semester_2 extends javax.swing.JFrame {

    public Connection con;
    public Statement stmt;
    public PreparedStatement prs;
    public login login;
    public isiSKS isiSKS;
    
    public void koneksian () {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendaftaran","root","");
            stmt = con.createStatement();
            
        } catch (Exception E) {
            JOptionPane.showMessageDialog(null,"Salah Prosedur");
        }
    
    }
    
    public semester_2() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    semester_2(JLabel parameter) {
        initComponents();
        setLocationRelativeTo(null);
        koneksian();
        
        //this.parameter = parameter;
        myName.setText(parameter.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        hasil1994 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        UTS6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        UAS7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        UTS7 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        UTS8 = new javax.swing.JTextField();
        hasilIP = new javax.swing.JButton();
        UAS8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UTS9 = new javax.swing.JTextField();
        UAS1 = new javax.swing.JTextField();
        UAS2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UAS9 = new javax.swing.JTextField();
        MUTU1 = new javax.swing.JLabel();
        lihMutu2 = new javax.swing.JButton();
        lihMutu3 = new javax.swing.JButton();
        lihMutu5 = new javax.swing.JButton();
        lihMutu4 = new javax.swing.JButton();
        lihMutu7 = new javax.swing.JButton();
        lihMutu6 = new javax.swing.JButton();
        lihMutu9 = new javax.swing.JButton();
        lihMutu8 = new javax.swing.JButton();
        lihMutu1 = new javax.swing.JButton();
        MUTU3 = new javax.swing.JLabel();
        MUTU4 = new javax.swing.JLabel();
        MUTU5 = new javax.swing.JLabel();
        MUTU6 = new javax.swing.JLabel();
        MUTU7 = new javax.swing.JLabel();
        MUTU8 = new javax.swing.JLabel();
        MUTU9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UTS3 = new javax.swing.JTextField();
        MUTU2 = new javax.swing.JLabel();
        UAS3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UTS4 = new javax.swing.JTextField();
        UAS4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UTS5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UAS5 = new javax.swing.JTextField();
        UTS1 = new javax.swing.JTextField();
        UAS6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        UTS2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        UTS10 = new javax.swing.JTextField();
        UAS10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        lihMutu10 = new javax.swing.JButton();
        MUTU10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        UTS11 = new javax.swing.JTextField();
        UAS11 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        lihMutu11 = new javax.swing.JButton();
        MUTU11 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        myName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        hasilIPK = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logout2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEMESTER 2");

        jLabel17.setText("3");

        jLabel18.setText("2");

        jLabel19.setText("2");

        jLabel20.setText("2");

        jLabel11.setText("Kalkulus");

        jLabel21.setText("2");

        jLabel22.setText("3");

        jLabel12.setText("Matematika Diskrit");

        jLabel23.setText("3");

        jLabel24.setText("1");

        jLabel13.setText("Prak. Algoritma & Pemrograman 2");

        jLabel25.setText("1");

        hasilIP.setText("hasil IP Semester Anda");
        hasilIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilIPActionPerformed(evt);
            }
        });

        jLabel5.setText("Nilai UTS");

        jLabel14.setText("Prak. Desain Web 2");

        jLabel6.setText("Nilai UAS");

        jLabel3.setText("SKS");

        jLabel7.setText("MUTU");

        MUTU1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU1ComponentAdded(evt);
            }
        });
        MUTU1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU1PropertyChange(evt);
            }
        });

        lihMutu2.setText("Lihat MUTU");
        lihMutu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu2ActionPerformed(evt);
            }
        });

        lihMutu3.setText("Lihat MUTU");
        lihMutu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu3ActionPerformed(evt);
            }
        });

        lihMutu5.setText("Lihat MUTU");
        lihMutu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu5ActionPerformed(evt);
            }
        });

        lihMutu4.setText("Lihat MUTU");
        lihMutu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu4ActionPerformed(evt);
            }
        });

        lihMutu7.setText("Lihat MUTU");
        lihMutu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu7ActionPerformed(evt);
            }
        });

        lihMutu6.setText("Lihat MUTU");
        lihMutu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu6ActionPerformed(evt);
            }
        });

        lihMutu9.setText("Lihat MUTU");
        lihMutu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu9ActionPerformed(evt);
            }
        });

        lihMutu8.setText("Lihat MUTU");
        lihMutu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu8ActionPerformed(evt);
            }
        });

        lihMutu1.setText("Lihat MUTU");
        lihMutu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu1ActionPerformed(evt);
            }
        });

        MUTU3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU3ComponentAdded(evt);
            }
        });
        MUTU3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU3PropertyChange(evt);
            }
        });

        MUTU4.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU4ComponentAdded(evt);
            }
        });
        MUTU4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU4PropertyChange(evt);
            }
        });

        MUTU5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU5ComponentAdded(evt);
            }
        });
        MUTU5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU5PropertyChange(evt);
            }
        });

        MUTU6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU6ComponentAdded(evt);
            }
        });
        MUTU6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU6PropertyChange(evt);
            }
        });

        MUTU7.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU7ComponentAdded(evt);
            }
        });
        MUTU7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU7PropertyChange(evt);
            }
        });

        MUTU8.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU8ComponentAdded(evt);
            }
        });
        MUTU8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU8PropertyChange(evt);
            }
        });

        MUTU9.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU9ComponentAdded(evt);
            }
        });
        MUTU9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU9PropertyChange(evt);
            }
        });

        jLabel8.setText("Sistem Informasi Manajemen");

        MUTU2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU2ComponentAdded(evt);
            }
        });
        MUTU2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU2PropertyChange(evt);
            }
        });

        jLabel15.setText("Mata Kuliah");

        jLabel9.setText("Interaksi Manusia & Komputer");

        jLabel10.setText("Kewarganegaraan");

        jLabel2.setText("Algoritma & Pemrograman 2");

        jLabel4.setText("Desain Web 2");

        jLabel28.setText("Sistem Operasi");

        jLabel29.setText("2");

        lihMutu10.setText("Lihat MUTU");
        lihMutu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu10ActionPerformed(evt);
            }
        });

        MUTU10.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU10ComponentAdded(evt);
            }
        });
        MUTU10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU10PropertyChange(evt);
            }
        });

        jLabel30.setText("Bahasa Indonesia");

        jLabel31.setText("2");

        lihMutu11.setText("Lihat MUTU");
        lihMutu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihMutu11ActionPerformed(evt);
            }
        });

        MUTU11.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                MUTU11ComponentAdded(evt);
            }
        });
        MUTU11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MUTU11PropertyChange(evt);
            }
        });

        jLabel32.setText("23");

        jLabel33.setText("Total SKS");

        jButton1.setText("Hasil IPK anda ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menu2.setText("Menu");

        jMenuItem3.setText("pilih semester");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu2.add(jMenuItem3);
        menu2.add(jSeparator1);

        logout2.setText("logout");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        menu2.add(logout2);
        menu2.add(jSeparator2);

        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu2.add(jMenuItem1);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hasilIPK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(myName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasil1994, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hasilIP)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel28)
                                .addComponent(jLabel30))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UTS1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UTS9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UTS10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UTS11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UAS1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS6, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS8, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                        .addComponent(UAS9)
                                        .addComponent(UAS10)
                                        .addComponent(UAS11))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MUTU1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MUTU11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lihMutu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu1)
                                .addComponent(lihMutu10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lihMutu11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGap(41, 41, 41)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(myName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addGap(22, 22, 22)
                .addComponent(hasil1994, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hasilIPK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lihMutu1)
                            .addComponent(MUTU1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel15))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(UTS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UAS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(UTS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UAS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lihMutu2)
                        .addComponent(MUTU2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(lihMutu3)
                        .addComponent(MUTU3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(lihMutu4)
                        .addComponent(MUTU4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(lihMutu5)
                        .addComponent(MUTU5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(lihMutu6)
                        .addComponent(MUTU6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(lihMutu7)
                        .addComponent(MUTU7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(lihMutu8)
                        .addComponent(MUTU8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(lihMutu9)
                        .addComponent(MUTU9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)
                        .addComponent(lihMutu10)
                        .addComponent(MUTU10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UAS11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UTS11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(lihMutu11)
                        .addComponent(MUTU11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                    .addComponent(hasilIP)
                    .addGap(43, 43, 43)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        try {
            login = new login();
            login.setVisible(true);
            this.dispose();
        } catch (Exception E) {
            
        }
    }//GEN-LAST:event_logout2ActionPerformed

    private void hasilIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilIPActionPerformed

        try {
            if((UTS1.getText().equals("") || UAS1.getText().equals("")) || (UTS2.getText().equals("") || UAS2.getText().equals("")) || (UTS3.getText().equals("") || UAS3.getText().equals("")) || (UTS4.getText().equals("") || UAS4.getText().equals("")) || (UTS5.getText().equals("") || UAS5.getText().equals("")) || (UTS6.getText().equals("") || UAS6.getText().equals("")) || (UTS7.getText().equals("") || UAS7.getText().equals("")) || (UTS8.getText().equals("") || UAS8.getText().equals("")) || (UTS9.getText().equals("") || UAS9.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "isi semua nilai anda terlebih dahulu");
            }
            else {

                String mutu1;
                String mutu2;
                String mutu3;
                String mutu4;
                String mutu5;
                String mutu6;
                String mutu7;
                String mutu8;
                String mutu9;
                String mutu10;
                String mutu11;

                int mutuValue1, mutuValue2, mutuValue3, mutuValue4, mutuValue5, mutuValue6, mutuValue7, mutuValue8, mutuValue9, mutuValue10, mutuValue11;
                float IPS;
                String HasilIPS;
                int value1_1, value1_2, value1_3;
                int value2_1, value2_2, value2_3;
                int value3_1, value3_2, value3_3;
                int value4_1, value4_2, value4_3;
                int value5_1, value5_2, value5_3;
                int value6_1, value6_2, value6_3;
                int value7_1, value7_2, value7_3;
                int value8_1, value8_2, value8_3;
                int value9_1, value9_2, value9_3;
                int value10_1, value10_2, value10_3;
                int value11_1, value11_2, value11_3;

                //mutu matkul pertama
                value1_1=Integer.valueOf(UTS1.getText());
                value1_2=Integer.valueOf(UAS1.getText());
                value1_3 = ((value1_1 + value1_2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu1=String.valueOf(value1_3);
                MUTU1.setText(mutu1);

                //mutu matkul kedua
                value2_1=Integer.valueOf(UTS2.getText());
                value2_2=Integer.valueOf(UAS2.getText());
                value2_3 = ((value2_1 + value2_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu2=String.valueOf(value2_3);
                MUTU2.setText(mutu2);

                //mutu matkul ketiga
                value3_1=Integer.valueOf(UTS3.getText());
                value3_2=Integer.valueOf(UAS3.getText());
                value3_3 = ((value3_1 + value3_2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu3=String.valueOf(value3_3);
                MUTU3.setText(mutu3);

                //mutu matkul keempat
                value4_1=Integer.valueOf(UTS4.getText());
                value4_2=Integer.valueOf(UAS4.getText());
                value4_3 = ((value4_1 + value4_2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu4=String.valueOf(value4_3);
                MUTU4.setText(mutu4);

                //mutu matkul kelima
                value5_1=Integer.valueOf(UTS5.getText());
                value5_2=Integer.valueOf(UAS5.getText());
                value5_3 = ((value5_1 + value5_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu5=String.valueOf(value5_3);
                MUTU5.setText(mutu5);

                //mutu matkul keenam
                value6_1=Integer.valueOf(UTS6.getText());
                value6_2=Integer.valueOf(UAS6.getText());
                value6_3 = ((value6_1 + value6_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu6=String.valueOf(value6_3);
                MUTU6.setText(mutu6);

                //mutu matkul ketujuh
                value7_1=Integer.valueOf(UTS7.getText());
                value7_2=Integer.valueOf(UAS7.getText());
                value7_3 = ((value7_1 + value7_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu7=String.valueOf(value7_3);
                MUTU7.setText(mutu7);

                //mutu matkul kedelapan
                value8_1=Integer.valueOf(UTS8.getText());
                value8_2=Integer.valueOf(UAS8.getText());
                value8_3 = ((value8_1 + value8_2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu8=String.valueOf(value8_3);
                MUTU8.setText(mutu8);

                //mutu matkul kesembilan
                value9_1=Integer.valueOf(UTS9.getText());
                value9_2=Integer.valueOf(UAS9.getText());
                value9_3 = ((value9_1 + value9_2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu9=String.valueOf(value9_3);
                MUTU9.setText(mutu9);
                
                //mutu matkul kesepuluh
                value10_1=Integer.valueOf(UTS10.getText());
                value10_2=Integer.valueOf(UAS10.getText());
                value10_3 = ((value10_1 + value10_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu10=String.valueOf(value10_3);
                MUTU10.setText(mutu10);
                
                //mutu matkul kesebelas
                value11_1=Integer.valueOf(UTS11.getText());
                value11_2=Integer.valueOf(UAS11.getText());
                value11_3 = ((value11_1 + value11_2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu11=String.valueOf(value11_3);
                MUTU11.setText(mutu11);

                mutuValue1=Integer.valueOf(MUTU1.getText());
                mutuValue2=Integer.valueOf(MUTU2.getText());
                mutuValue3=Integer.valueOf(MUTU3.getText());
                mutuValue4=Integer.valueOf(MUTU4.getText());
                mutuValue5=Integer.valueOf(MUTU5.getText());
                mutuValue6=Integer.valueOf(MUTU6.getText());
                mutuValue7=Integer.valueOf(MUTU7.getText());
                mutuValue8=Integer.valueOf(MUTU8.getText());
                mutuValue9=Integer.valueOf(MUTU9.getText());
                mutuValue10=Integer.valueOf(MUTU10.getText());
                mutuValue11=Integer.valueOf(MUTU11.getText());
                IPS = (mutuValue1+mutuValue2+mutuValue3+mutuValue4+mutuValue5+mutuValue6+mutuValue7+mutuValue8+mutuValue9+mutuValue10+mutuValue11)/23;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                HasilIPS=String.valueOf(IPS);
                hasil1994.setText(HasilIPS);
                try {
                String sql = "update mahasiswa set nilai_SMT2 = '"+hasil1994.getText()+"' where nama_Mahasiswa = '"+myName.getText()+"'";
                //ResultSet rset = stmt.executeQuery(sql);
                prs = con.prepareStatement(sql);
                prs.execute();
                JOptionPane.showMessageDialog(null, "Nilai semester 2 anda sudah di update");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "salah prosedur " +e);
                }
                //String sql = "update mahasiswa set nilai_SMST1 = '"+hasil1946.getText()+"' where ID='1'";
                //ResultSet rset = stmt.executeQuery(sql);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "terjadi kesalahan" +e);
        }

    }//GEN-LAST:event_hasilIPActionPerformed

    private void MUTU1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU1ComponentAdded

    }//GEN-LAST:event_MUTU1ComponentAdded

    private void MUTU1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU1PropertyChange

    }//GEN-LAST:event_MUTU1PropertyChange

    private void lihMutu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu2ActionPerformed
        try{
            if (UTS2.getText().equals("") || UAS2.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu2;

                value1=Integer.valueOf(UTS2.getText());
                value2=Integer.valueOf(UAS2.getText());
                value3 = ((value1 + value2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu2=String.valueOf(value3);
                MUTU2.setText(mutu2);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu2ActionPerformed

    private void lihMutu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu3ActionPerformed
        try{
            if (UTS3.getText().equals("") || UAS3.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu3;

                value1=Integer.valueOf(UTS3.getText());
                value2=Integer.valueOf(UAS3.getText());
                value3 = ((value1 + value2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu3=String.valueOf(value3);
                MUTU3.setText(mutu3);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu3ActionPerformed

    private void lihMutu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu5ActionPerformed
        try{
            if (UTS5.getText().equals("") || UAS5.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu5;

                value1=Integer.valueOf(UTS5.getText());
                value2=Integer.valueOf(UAS5.getText());
                value3 = ((value1 + value2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu5=String.valueOf(value3);
                MUTU5.setText(mutu5);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu5ActionPerformed

    private void lihMutu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu4ActionPerformed
        try{
            if (UTS4.getText().equals("") || UAS4.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu4;

                value1=Integer.valueOf(UTS2.getText());
                value2=Integer.valueOf(UAS2.getText());
                value3 = ((value1 + value2)/2)*2;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu4=String.valueOf(value3);
                MUTU4.setText(mutu4);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu4ActionPerformed

    private void lihMutu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu7ActionPerformed
        try{
            if (UTS7.getText().equals("") || UAS7.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu7;

                value1=Integer.valueOf(UTS7.getText());
                value2=Integer.valueOf(UAS7.getText());
                value3 = ((value1 + value2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu7=String.valueOf(value3);
                MUTU7.setText(mutu7);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu7ActionPerformed

    private void lihMutu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu6ActionPerformed
        try{
            if (UTS6.getText().equals("") || UAS6.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu6;

                value1=Integer.valueOf(UTS6.getText());
                value2=Integer.valueOf(UAS6.getText());
                value3 = ((value1 + value2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu6=String.valueOf(value3);
                MUTU6.setText(mutu6);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu6ActionPerformed

    private void lihMutu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu9ActionPerformed
        try{
            if (UTS9.getText().equals("") || UAS9.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu9;

                value1=Integer.valueOf(UTS9.getText());
                value2=Integer.valueOf(UAS9.getText());
                value3 = ((value1 + value2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu9=String.valueOf(value3);
                MUTU9.setText(mutu9);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu9ActionPerformed

    private void lihMutu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu8ActionPerformed
        try{
            if (UTS8.getText().equals("") || UAS8.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu8;

                value1=Integer.valueOf(UTS8.getText());
                value2=Integer.valueOf(UAS8.getText());
                value3 = ((value1 + value2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu8=String.valueOf(value3);
                MUTU8.setText(mutu8);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu8ActionPerformed

    private void lihMutu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu1ActionPerformed
        try{
            if (UTS1.getText().equals("") || UAS1.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu1;

                value1=Integer.valueOf(UTS1.getText());
                value2=Integer.valueOf(UAS1.getText());
                value3 = ((value1 + value2)/2)*3;
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu1=String.valueOf(value3);
                MUTU1.setText(mutu1);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu1ActionPerformed

    private void MUTU3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU3ComponentAdded

    private void MUTU3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU3PropertyChange

    private void MUTU4ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU4ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU4ComponentAdded

    private void MUTU4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU4PropertyChange

    private void MUTU5ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU5ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU5ComponentAdded

    private void MUTU5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU5PropertyChange

    private void MUTU6ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU6ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU6ComponentAdded

    private void MUTU6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU6PropertyChange

    private void MUTU7ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU7ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU7ComponentAdded

    private void MUTU7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU7PropertyChange

    private void MUTU8ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU8ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU8ComponentAdded

    private void MUTU8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU8PropertyChange

    private void MUTU9ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU9ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU9ComponentAdded

    private void MUTU9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU9PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU9PropertyChange

    private void MUTU2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU2ComponentAdded

    private void MUTU2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU2PropertyChange

    private void lihMutu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu10ActionPerformed
        try{
            if (UTS10.getText().equals("") || UAS10.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu10;

                value1=Integer.valueOf(UTS10.getText());
                value2=Integer.valueOf(UAS10.getText());
                value3 = ((value1 + value2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu10=String.valueOf(value3);
                MUTU10.setText(mutu10);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu10ActionPerformed

    private void MUTU10ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU10ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU10ComponentAdded

    private void MUTU10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU10PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU10PropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int out; 
        out = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Ingin Keluar ?"); 
        if(out==JOptionPane.YES_OPTION){ 
            System.exit(0); 
        } 
        else{}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
        isiSKS = new isiSKS(myName);
        isiSKS.setVisible(true);
        this.dispose();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"salah "+e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void lihMutu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihMutu11ActionPerformed
        try{
            if (UTS11.getText().equals("") || UAS11.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"nilai UTS dan UAS diisi terlebih dahulu");
            } else {
                int value1;
                int value2;
                int value3;
                String mutu11;

                value1=Integer.valueOf(UTS11.getText());
                value2=Integer.valueOf(UAS11.getText());
                value3 = ((value1 + value2)/2);
                /** mengubah tipe data ke String agar dapat
                * ditampilkan kembali pada Form
                */
                mutu11=String.valueOf(value3);
                MUTU11.setText(mutu11);
            }
        } catch (Exception E){
            JOptionPane.showMessageDialog(null, "keslahan pada "+E);
        }
    }//GEN-LAST:event_lihMutu11ActionPerformed

    private void MUTU11ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_MUTU11ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU11ComponentAdded

    private void MUTU11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MUTU11PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_MUTU11PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ip_smt1 = null;
        String ip_smt2 = null;
        String manipulasi;
        int IPK;
        int IP_Semester1;
        int IP_Semester2;
        
        if((UTS1.getText().equals("") || UAS1.getText().equals("")) || (UTS2.getText().equals("") || UAS2.getText().equals("")) || (UTS3.getText().equals("") || UAS3.getText().equals("")) || (UTS4.getText().equals("") || UAS4.getText().equals("")) || (UTS5.getText().equals("") || UAS5.getText().equals("")) || (UTS6.getText().equals("") || UAS6.getText().equals("")) || (UTS7.getText().equals("") || UAS7.getText().equals("")) || (UTS8.getText().equals("") || UAS8.getText().equals("")) || (UTS9.getText().equals("") || UAS9.getText().equals(""))){
        JOptionPane.showMessageDialog(null, "isi ulo");    
        }
         else {
        try {
        String sql = "select * from mahasiswa where nama_Mahasiswa = '"+myName.getText()+"'";
        ResultSet rset = stmt.executeQuery(sql);
        while (rset.next()) {
            ip_smt1 = rset.getString("nilai_SMT1");
            ip_smt2 = rset.getString("nilai_SMT2");
           
        }
        IP_Semester1 = Integer.parseInt(ip_smt1);
        IP_Semester2 = Integer.parseInt(ip_smt2);
        IPK = (IP_Semester1 + IP_Semester2) / 2 ;
        manipulasi = String.valueOf(IPK);
        hasilIPK.setText(manipulasi);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "perhitungan gagal");
        }
        }
        
        try{
        String sql = "update mahasiswa set IPK = '"+hasilIPK.getText()+"' where nama_Mahasiswa = '"+myName.getText()+"'";
        prs = con.prepareStatement(sql);
        prs.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data salah");
        }
        
        
        
        //IPK = ip_smt1 + ip_smt2/2;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(semester_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(semester_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(semester_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(semester_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new semester_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MUTU1;
    private javax.swing.JLabel MUTU10;
    private javax.swing.JLabel MUTU11;
    private javax.swing.JLabel MUTU2;
    private javax.swing.JLabel MUTU3;
    private javax.swing.JLabel MUTU4;
    private javax.swing.JLabel MUTU5;
    private javax.swing.JLabel MUTU6;
    private javax.swing.JLabel MUTU7;
    private javax.swing.JLabel MUTU8;
    private javax.swing.JLabel MUTU9;
    private javax.swing.JTextField UAS1;
    private javax.swing.JTextField UAS10;
    private javax.swing.JTextField UAS11;
    private javax.swing.JTextField UAS2;
    private javax.swing.JTextField UAS3;
    private javax.swing.JTextField UAS4;
    private javax.swing.JTextField UAS5;
    private javax.swing.JTextField UAS6;
    private javax.swing.JTextField UAS7;
    private javax.swing.JTextField UAS8;
    private javax.swing.JTextField UAS9;
    private javax.swing.JTextField UTS1;
    private javax.swing.JTextField UTS10;
    private javax.swing.JTextField UTS11;
    private javax.swing.JTextField UTS2;
    private javax.swing.JTextField UTS3;
    private javax.swing.JTextField UTS4;
    private javax.swing.JTextField UTS5;
    private javax.swing.JTextField UTS6;
    private javax.swing.JTextField UTS7;
    private javax.swing.JTextField UTS8;
    private javax.swing.JTextField UTS9;
    private javax.swing.JLabel hasil1994;
    private javax.swing.JButton hasilIP;
    private javax.swing.JLabel hasilIPK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton lihMutu1;
    private javax.swing.JButton lihMutu10;
    private javax.swing.JButton lihMutu11;
    private javax.swing.JButton lihMutu2;
    private javax.swing.JButton lihMutu3;
    private javax.swing.JButton lihMutu4;
    private javax.swing.JButton lihMutu5;
    private javax.swing.JButton lihMutu6;
    private javax.swing.JButton lihMutu7;
    private javax.swing.JButton lihMutu8;
    private javax.swing.JButton lihMutu9;
    private javax.swing.JMenuItem logout2;
    private javax.swing.JMenu menu2;
    private javax.swing.JLabel myName;
    // End of variables declaration//GEN-END:variables
}
